### ISSUE TITLE
[ISSUE] Undefined variable $response when TELESCOPE_TAG_STATUS is enabled

### ISSUE THREAD

**Issue by DavidPuzder** [wamesk/laravel-telescope#1]
<img width="259" alt="SCR-20240209-neoy" src="https://github.com/wamesk/laravel-telescope/assets/36508590/96ba4561-242f-43c4-9e7f-4ca4e0a2adf9">

<img width="1390" alt="SCR-20240209-nevp" src="https://github.com/wamesk/laravel-telescope/assets/36508590/d79fa7f1-86d6-4f22-84c1-04f90d3bcbc7">

<img width="332" alt="SCR-20240209-nezw" src="https://github.com/wamesk/laravel-telescope/assets/36508590/7e3987b4-4ec5-46aa-a7fc-fbd04ed8f3bc">

**Comment by wamesro** [comment]
Thanx @DavidPuzder 
I edited the attributes for all tags

[https://github.com/wamesk/laravel-telescope/releases/tag/1.0.1]()
